# Generated by Django 5.1.4 on 2025-01-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TakServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='A unique identifier for the certificate', max_length=200, unique=True)),
                ('dns_name', models.CharField(help_text='DNS name for the server', max_length=30, unique=True)),
                ('cert_trust', models.FileField(help_text='Upload the trusted certificate file', upload_to='certificates/certtrust/')),
                ('cert_private', models.FileField(help_text='Upload the private certificate file', upload_to='certificates/certprivate/')),
            ],
        ),
    ]
