# Generated by Django 5.1.5 on 2025-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takserver',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the server'),
        ),
        migrations.AlterField(
            model_name='takserver',
            name='cert_private',
            field=models.FileField(help_text='Upload the private certificate file - PEM Format', upload_to='certificates/certprivate/'),
        ),
        migrations.AlterField(
            model_name='takserver',
            name='cert_trust',
            field=models.FileField(help_text='Upload the trusted certificate file - PEM Format', upload_to='certificates/certtrust/'),
        ),
    ]
