# Generated by Django 5.2.1 on 2025-05-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takserver', '0002_takserver_notes_alter_takserver_cert_private_and_more'),
    ]

    operations = [
        # No operations needed since the column doesn't exist
    ]
