# Generated by Django 5.2.1 on 2025-05-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takserver', '0002_takserver_notes_alter_takserver_cert_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takserver',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
