# Generated by Django 5.2.8 on 2026-01-11 12:55

import takserver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takserver', '0004_migrate_certificate_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takserver',
            name='cert_private',
            field=models.FileField(help_text='Upload the private certificate file - PEM Format', storage=takserver.models.get_private_storage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='takserver',
            name='cert_trust',
            field=models.FileField(help_text='Upload the trusted certificate file - PEM Format', storage=takserver.models.get_trust_storage, upload_to=''),
        ),
    ]
