# Generated by Django 5.2.10 on 2026-01-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takserver', '0005_alter_takserver_cert_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Unique identifier for this gateway (e.g., 'mesh-gateway-1')", max_length=100, unique=True)),
                ('mqtt_host', models.CharField(help_text="MQTT broker hostname (e.g., 'mosquitto' or 'mqtt.example.com')", max_length=255)),
                ('mqtt_port', models.PositiveIntegerField(default=1883, help_text='MQTT broker port (default: 1883)')),
                ('mqtt_username', models.CharField(blank=True, help_text='MQTT username (optional)', max_length=100)),
                ('mqtt_password', models.CharField(blank=True, help_text='MQTT password (optional, stored encrypted)', max_length=100)),
                ('mesh_channel', models.CharField(default='takmesh', help_text="Meshtastic channel name to bridge (default: 'takmesh')", max_length=50)),
                ('gateway_uid', models.CharField(default='takmesh-gateway', help_text='Unique ID for this gateway in TAK', max_length=100)),
                ('gateway_callsign', models.CharField(default='TAKMESH', help_text='Callsign displayed in TAK clients', max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable this gateway for bridging')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this gateway configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('takserver', models.ForeignKey(help_text='TAK Server to bridge MQTT messages to', on_delete=django.db.models.deletion.PROTECT, related_name='mqtt_gateways', to='takserver.takserver')),
            ],
            options={
                'verbose_name': 'MQTT Gateway',
                'verbose_name_plural': 'MQTT Gateways',
                'ordering': ['name'],
            },
        ),
    ]
