# Generated by Django 5.2.10 on 2026-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takserver', '0006_add_mqttgateway_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttgateway',
            name='mqtt_subscribe_topic',
            field=models.CharField(default='msh/US/SOA/2/json/takmesh/#', help_text="MQTT topic pattern to subscribe to (e.g., 'msh/US/SOA/2/json/takmesh/#')", max_length=255),
        ),
    ]
