# Generated by Django 5.1.3 on 2024-11-11 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_first_name', models.CharField(max_length=20)),
                ('requestor_last_name', models.CharField(max_length=30)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('requestor_phone', models.CharField(max_length=12)),
                ('assistance_first_name', models.CharField(blank=True, max_length=20)),
                ('assistance_last_name', models.CharField(blank=True, max_length=30)),
                ('assistance_email', models.EmailField(blank=True, max_length=254)),
                ('assistance_phone', models.CharField(blank=True, max_length=12)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('assistance_type', models.CharField(choices=[('evacuation', 'Evacuation'), ('re_supply', 'Re-supply'), ('welfare_check', 'Welfare check'), ('other', 'Other (please describe)')], max_length=20)),
                ('assistance_description', models.TextField(blank=True, null=True)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('contact_methods', models.TextField(blank=True, null=True)),
                ('medical_needs', models.TextField(blank=True, null=True)),
                ('supplies_needed', models.TextField(blank=True, null=True)),
                ('welfare_check_info', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('field_op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to='aidrequests.fieldop')),
            ],
        ),
    ]
