# Generated by Django 5.1.3 on 2024-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='group_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
