# Generated by Django 5.1.2 on 2024-11-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='assistance_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='assistance_first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='assistance_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='assistance_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requestor_first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requestor_last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='street_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
