# Generated by Django 5.1.4 on 2025-01-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunSQL(
            """
            INSERT INTO aidrequests_aidtype (slug, name) VALUES
            ('evacuation', 'Evacuation'),
            ('re_supply', 'Re-supply'),
            ('welfare_check', 'Welfare check'),
            ('other', 'Other');
            """
        ),
        migrations.RenameField(
            model_name='aidrequest',
            old_name='assistance_description',
            new_name='aid_description',
        ),
        migrations.RenameField(
            model_name='aidrequest',
            old_name='assistance_email',
            new_name='aid_email',
        ),
        migrations.RenameField(
            model_name='aidrequest',
            old_name='assistance_first_name',
            new_name='aid_first_name',
        ),
        migrations.RenameField(
            model_name='aidrequest',
            old_name='assistance_last_name',
            new_name='aid_last_name',
        ),
        migrations.RenameField(
            model_name='aidrequest',
            old_name='assistance_phone',
            new_name='aid_phone',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='assistance_type',
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='aid_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidrequests.aidtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldop',
            name='aid_types',
            field=models.ManyToManyField(blank=True, default=1, related_name='field_ops', to='aidrequests.aidtype'),
        ),
    ]
