# Generated by Django 5.1.2 on 2024-11-04 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0002_alter_aidrequest_assistance_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='region_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidrequests.regionresponse'),
        ),
    ]
