# Generated by Django 5.1.4 on 2025-01-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0002_aidtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidtype',
            options={'verbose_name': 'Aid Type', 'verbose_name_plural': 'Aid Types'},
        ),
    ]
