# Generated by Django 5.1.3 on 2024-11-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0003_alter_aidrequest_state_alter_aidrequest_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
