# Generated by Django 5.1.4 on 2025-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0004_aidtype_icon_color_aidtype_icon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='icon_name',
            field=models.CharField(choices=[('marker', 'marker'), ('marker-thick', 'marker-thick'), ('marker-circle', 'marker-circle'), ('marker-flat', 'marker-flat'), ('marker-square', 'marker-square'), ('marker-square-cluster', 'marker-square-cluster'), ('marker-arrow', 'marker-arrow'), ('marker-ball-pin', 'marker-ball-pin'), ('marker-square-rounded', 'marker-square-rounded'), ('marker-square-rounded-cluster', 'marker-square-rounded-cluster'), ('flag', 'flag'), ('flag-triangle', 'flag-triangle'), ('triangle', 'triangle'), ('triangle-thick', 'triangle-thick'), ('triangle-arrow-up', 'triangle-arrow-up'), ('triangle-arrow-left', 'triangle-arrow-left'), ('hexagon', 'hexagon'), ('hexagon-thick', 'hexagon-thick'), ('hexagon-rounded', 'hexagon-rounded'), ('hexagon-rounded-thick', 'hexagon-rounded-thick'), ('pin', 'pin'), ('pin-round', 'pin-round'), ('rounded-square', 'rounded-square'), ('rounded-square-thick', 'rounded-square-thick'), ('arrow-up', 'arrow-up'), ('arrow-up-thin', 'arrow-up-thin'), ('car', 'car')], default='helicopter', max_length=30),
        ),
    ]
