# Generated by Django 5.1.3 on 2024-11-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0004_aidrequest_country_alter_aidrequest_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('candidate', 'Candidate'), ('other', 'Other')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('azure_maps', 'Azure Maps'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('aid_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='aidrequests.aidrequest')),
            ],
        ),
    ]
