# Generated by Django 5.1.5 on 2025-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0006_fieldop_tak_server_alter_aidtype_icon_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtype',
            name='cot_icon',
            field=models.CharField(blank=True, choices=[('red_diamond', 'red_diamond'), ('green_square_x', 'green_square_x'), ('yellow_blob', 'yellow_blob'), ('a-n-x-i-s', 'a-n-x-i-s'), ('a-n-g-u-c', 'a-n-g-u-c'), ('a-n-g-u-c-i', 'a-n-g-u-c-i'), ('a-n-g', 'a-n-g'), ('green_square', 'green_square'), ('food', 'food'), ('blob-purple-truck', 'blob-purple-truck')], max_length=50, null=True),
        ),
    ]
