# Generated by Django 5.1.3 on 2024-11-20 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0006_rename_notes_aidlocation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
