# Generated by Django 5.1.3 on 2024-11-20 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0007_aidrequest_created_at_aidrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fieldop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
