# Generated by Django 5.1.5 on 2025-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0007_aidtype_cot_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='cot_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
