# Generated by Django 5.1.7 on 2025-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0008_alter_aidtype_cot_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), (None, 'None')], default=None, max_length=10, null=True),
        ),
    ]
