# Generated by Django 5.2 on 2025-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0009_alter_aidrequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldop',
            name='disable_cot',
            field=models.BooleanField(default=False, help_text='When enabled, COT (Common Operating Template) will be disabled for this field operation'),
        ),
    ]
