# Generated by Django 5.1.3 on 2024-11-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0009_fieldop_created_by_fieldop_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_locations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidlocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_locations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requestor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requestor_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
