# Generated by Django 5.2 on 2025-05-01 14:21

from django.db import migrations, models

def set_default_ring_size(apps, schema_editor):
    FieldOp = apps.get_model('aidrequests', 'FieldOp')
    # Only set ring_size where it's currently null
    FieldOp.objects.filter(ring_size__isnull=True).update(ring_size=10)

class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0010_fieldop_disable_cot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldop',
            name='ring_size',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Ring size in kilometers (optional, must be greater than 0 if set)', null=True),
        ),
        migrations.RunPython(set_default_ring_size, migrations.RunPython.noop),
    ]
