# Generated by Django 5.1.3 on 2024-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0010_aidlocation_created_by_aidlocation_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='priority',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('other', 'Other')], default='new', max_length=10),
        ),
    ]
