# Generated by Django 5.1.3 on 2024-11-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0011_aidrequest_priority_aidrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('other', 'Other')], default='new', max_length=10),
        ),
    ]
