# Generated by Django 5.2 on 2025-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0011_fieldop_ring_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldop',
            name='disable_cot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fieldop',
            name='ring_size',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='kilometers', null=True),
        ),
    ]
