# Generated by Django 5.2 on 2025-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0012_alter_fieldop_disable_cot_alter_fieldop_ring_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldop',
            name='notify',
            field=models.ManyToManyField(blank=True, to='aidrequests.fieldopnotify'),
        ),
    ]
