# Generated by Django 5.1.3 on 2024-12-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0013_aidrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequestlog',
            name='associated_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='aidrequests.aidrequest'),
        ),
    ]
