# Generated by Django 5.2.2 on 2025-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0013_alter_fieldop_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('unsubmitted', 'Unsubmitted'), ('other', 'Other')], default='new', max_length=20),
        ),
    ]
