# Generated by Django 5.1.3 on 2024-12-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0014_alter_aidrequestlog_associated_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aidrequestlog',
            old_name='associated_object',
            new_name='aid_request',
        ),
    ]
