# Generated by Django 5.2.2 on 2025-06-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0014_aidrequest_latitude_aidrequest_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidrequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('other', 'Other')], default='new', max_length=10),
        ),
    ]
