# Generated by Django 5.2.2 on 2025-06-18 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0015_remove_aidrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtype',
            name='weight',
            field=models.PositiveIntegerField(default=5, help_text='1-10, lower is higher priority for lists', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
