# Generated by Django 5.1.3 on 2024-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0015_rename_associated_object_aidrequestlog_aid_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOpNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('email-individual', 'Email Individual'), ('email-group', 'Email Group'), ('sms', 'SMS')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sms_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
