# Generated by Django 5.1.3 on 2024-12-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0016_fieldopnotify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldopnotify',
            options={'verbose_name': 'Notify Address', 'verbose_name_plural': 'Notify Addresses'},
        ),
    ]
