# Generated by Django 5.2.3 on 2025-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0016_aidtype_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='street_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
