# Generated by Django 5.1.3 on 2024-12-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0017_alter_fieldopnotify_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidlocation',
            options={'verbose_name': 'Aid Location', 'verbose_name_plural': 'Aid Locations'},
        ),
        migrations.AlterModelOptions(
            name='aidrequest',
            options={'verbose_name': 'Aid Request', 'verbose_name_plural': 'Aid Requests'},
        ),
        migrations.AlterModelOptions(
            name='aidrequestlog',
            options={'verbose_name': 'Aid Request Log', 'verbose_name_plural': 'Aid Request Logs'},
        ),
        migrations.AlterModelOptions(
            name='fieldop',
            options={'verbose_name': 'Field Operation', 'verbose_name_plural': 'Field Operations'},
        ),
    ]
