# Generated by Django 5.2.3 on 2025-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0017_alter_aidrequest_city_alter_aidrequest_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldop',
            name='country',
            field=models.CharField(blank=True, default='USA', help_text='Default country for new aid requests.', max_length=30),
        ),
    ]
