# Generated by Django 5.2.3 on 2025-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0018_fieldop_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='use_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
