# Generated by Django 5.1.3 on 2024-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0018_alter_aidlocation_options_alter_aidrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldopnotify',
            name='field_ops',
            field=models.ManyToManyField(related_name='notifications', to='aidrequests.fieldop'),
        ),
    ]
