# Generated by Django 5.1.3 on 2024-12-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0019_fieldopnotify_field_ops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldopnotify',
            name='field_ops',
        ),
        migrations.AddField(
            model_name='fieldop',
            name='notifications',
            field=models.ManyToManyField(related_name='field_ops', to='aidrequests.fieldopnotify'),
        ),
    ]
