# Generated by Django 5.2.3 on 2025-06-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0019_aidrequest_use_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='use_whatsapp_aid',
            field=models.BooleanField(default=False),
        ),
    ]
