# Generated by Django 5.1.3 on 2024-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0020_remove_fieldopnotify_field_ops_fieldop_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldop',
            old_name='notifications',
            new_name='notifies',
        ),
    ]
