# Generated by Django 5.2.3 on 2025-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0020_aidrequest_use_whatsapp_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='aid_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requestor_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
