# Generated by Django 5.1.3 on 2024-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0021_rename_notifications_fieldop_notifies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldop',
            name='notifies',
            field=models.ManyToManyField(to='aidrequests.fieldopnotify'),
        ),
    ]
