# Generated by Django 5.2.3 on 2025-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0021_alter_aidrequest_aid_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='requestor_first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requestor_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
