# Generated by Django 5.1.3 on 2024-12-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0022_alter_fieldop_notifies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldop',
            old_name='notifies',
            new_name='notify',
        ),
    ]
