# Generated by Django 5.2.6 on 2025-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0023_rename_requester_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidlocation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('azure_maps', 'Azure Maps'), ('other', 'Other'), ('user_picked', 'User Picked')], max_length=20),
        ),
    ]
