# Generated by Django 5.2.6 on 2025-09-18 11:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0024_alter_aidlocation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldop',
            name='country',
            field=django_countries.fields.CountryField(default='US', help_text='Default country for new aid requests.', max_length=2),
        ),
    ]
