# Generated by Django 5.1.4 on 2024-12-14 14:50
from django.db import migrations
import informs.utils


def gen_uid(apps, schema_editor):
    Locations = apps.get_model("aidrequests", "AidLocation")
    for row in Locations.objects.all():
        row.uid = informs.utils.takuid_new()
        row.save(update_fields=["uid"])

class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0024_aidlocation_uid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uid, reverse_code=migrations.RunPython.noop),
    ]
