# Generated by Django 5.2.6 on 2025-09-18 11:47

from django.db import migrations
import django_countries


def convert_country_data(apps, schema_editor):
    FieldOp = apps.get_model('aidrequests', 'FieldOp')
    for field_op in FieldOp.objects.all():
        country_name = field_op.country
        if isinstance(country_name, str):
            country_code = django_countries.countries.by_name(country_name)
            if country_code:
                field_op.country = country_code
                field_op.save()

def reverse_country_data(apps, schema_editor):
    FieldOp = apps.get_model('aidrequests', 'FieldOp')
    for field_op in FieldOp.objects.all():
        country_code = field_op.country
        country = dict(django_countries.countries).get(country_code)
        if country:
            field_op.country = country.name
            field_op.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0025_country_field'),
    ]

    operations = [
        migrations.RunPython(convert_country_data, reverse_code=reverse_country_data),
    ]
