# Generated by Django 5.2.6 on 2025-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0026_convert_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidlocation',
            name='free_form_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aidlocation',
            name='geocode_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
