# Generated by Django 5.1.4 on 2024-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0026_aidlocation_uidnotnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidlocation',
            name='address_found',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aidlocation',
            name='address_searched',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aidlocation',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
