# Generated by Django 5.2.6 on 2025-09-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0027_aidlocation_free_form_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidlocation',
            name='address_found',
        ),
    ]
