# Generated by Django 5.1.4 on 2024-12-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0028_aidlocation_map_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidlocation',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
