# Generated by Django 5.2.6 on 2025-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0028_remove_aidlocation_address_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidlocation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('azure_maps', 'Azure Maps'), ('address_provided', 'Address Provided'), ('other', 'Other'), ('user_picked', 'User Picked')], max_length=20),
        ),
    ]
