# Generated by Django 5.1.4 on 2024-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0029_alter_aidlocation_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='assistance_type',
            field=models.CharField(choices=[('evacuation', 'Evacuation'), ('re_supply', 'Re-supply'), ('welfare_check', 'Welfare check'), ('other', 'Other')], max_length=20),
        ),
    ]
