# Generated by Django 5.2.6 on 2025-10-27 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0029_alter_aidlocation_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=10)),
                ('message', models.TextField()),
                ('aid_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='aidrequests.aidrequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AidRequestLog',
        ),
    ]
