# Generated by Django 5.1.4 on 2024-12-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0030_alter_aidrequest_assistance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldop',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fieldop',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
