# Generated by Django 5.2.7 on 2025-10-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0030_action_log_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='log_type',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System'), ('map', 'Map')], default='user', max_length=10),
        ),
    ]
