# Generated by Django 5.2.7 on 2025-10-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0031_actionlog_map_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='log_type',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System'), ('location', 'Location')], default='user', max_length=10),
        ),
    ]
