# Generated by Django 5.2.7 on 2025-10-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0032_actionlog_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidlocation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('azure_maps', 'Azure Maps'), ('address_provided', 'Address Provided'), ('device_location', 'Device Location'), ('other', 'Other'), ('user_picked', 'User Picked')], max_length=20),
        ),
    ]
