# Generated by Django 5.2.7 on 2025-10-30 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0033_add_device_location_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={},
        ),
        migrations.AddField(
            model_name='actionlog',
            name='agent_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='event_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='is_markdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
