# Generated by Django 5.2.7 on 2025-10-30 23:44
import json
from django.db import migrations

def migrate_actionlog_data(apps, schema_editor):
    ActionLog = apps.get_model('aidrequests', 'ActionLog')
    for log in ActionLog.objects.all():
        if log.message:
            try:
                data = json.loads(log.message)
                log.event_name = data.get('event_name', '')
                log.event_text = data.get('event_text', '')
                log.note = data.get('note', '')
                log.is_markdown = data.get('is_markdown', False)
                log.agent_name = data.get('agent', '')
            except (json.JSONDecodeError, TypeError):
                # Handle old, non-JSON messages
                log.note = log.message
                log.event_name = 'Legacy Note'
                log.is_markdown = False # Assume not markdown
            log.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0034_refactor_actionlog_model'),
    ]

    operations = [
        migrations.RunPython(migrate_actionlog_data, reverse_code=migrations.RunPython.noop),
    ]
