# Generated by Django 5.2.7 on 2025-10-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0035_migrate_actionlog_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='message',
        ),
    ]
