# Generated by Django 5.2.7 on 2025-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0036_remove_message_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='note_is_markdown',
            field=models.BooleanField(default=False, help_text='Flag for note markdown'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='is_markdown',
            field=models.BooleanField(default=False, help_text='Flag for event_text markdown'),
        ),
    ]
