# Generated by Django 5.2.7 on 2025-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0037_add_note_is_markdown_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='is_markdown',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='note_is_markdown',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='note_markdown',
            field=models.BooleanField(default=False, help_text='Flag for note markdown'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='text_markdown',
            field=models.BooleanField(default=False, help_text='Flag for event_text markdown'),
        ),
    ]
