# Generated by Django 5.2.7 on 2025-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0038_rename_markdown_flags_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidrequest',
            name='use_whatsapp',
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='requester_phone_is_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requester_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requester_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
