# Generated by Django 5.2.7 on 2025-11-04 20:10

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0039_remove_aidrequest_use_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
