# Generated by Django 5.2.8 on 2025-11-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0040_alter_aidrequest_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldop',
            name='latitude',
            field=models.DecimalField(decimal_places=5, help_text='Maximum 5 decimal places.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldop',
            name='longitude',
            field=models.DecimalField(decimal_places=5, help_text='Maximum 5 decimal places.', max_digits=9),
        ),
    ]
