# Generated by Django 5.2.8 on 2025-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0041_alter_fieldop_latitude_alter_fieldop_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldop',
            name='ring_size',
            field=models.PositiveIntegerField(default=1, help_text='kilometers'),
        ),
    ]
