# Generated by Django 5.2.8 on 2025-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0042_alter_fieldop_ring_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
