# Generated by Django 5.2.8 on 2025-11-12 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0043_alter_actionlog_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='text_markdown',
        ),
        migrations.AlterField(
            model_name='fieldop',
            name='latitude',
            field=models.DecimalField(decimal_places=5, help_text='Maximum 5 decimal places.', max_digits=8, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='fieldop',
            name='longitude',
            field=models.DecimalField(decimal_places=5, help_text='Maximum 5 decimal places.', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
