# Generated by Django 5.2.8 on 2025-11-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0044_remove_actionlog_text_markdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtype',
            name='bs_icon',
            field=models.CharField(blank=True, help_text='Name of the Bootstrap icon to use.', max_length=50, null=True),
        ),
    ]
