# Generated by Django 5.2.8 on 2025-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0045_aidtype_bs_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='log_type',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System'), ('location', 'Location'), ('status', 'Status'), ('priority', 'Priority')], default='user', max_length=10),
        ),
    ]
