# Generated by Django 5.2.8 on 2025-11-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidrequests', '0046_alter_actionlog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='log_type',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System'), ('location', 'Location'), ('status', 'Status'), ('priority', 'Priority'), ('alert', 'Alert')], default='user', max_length=10),
        ),
    ]
