version: '3'

services:
  test-informs:
    build:
      context: .
    image: informs-app
    env_file:
      - env/django.env
    entrypoint: /opt/app/docker-entrypoint.sh
    command: bash -c "cd /opt/app/informs && coverage run --source='.' manage.py test $(find . -path ./tests -prune -o -name 'test*.py' -print | sed 's|^\./||; s|\.py$||; s|/|.|g')"
    volumes:
      - ./run_tests.sh:/opt/app/run_tests.sh
      - informs_test_staticfiles:/opt/app/static_files
      - informs_test_db:/opt/app/db
      - test_certs:/opt/app/certs:z
      - ./reports:/opt/app/reports

  test-coverage:
    build:
      context: .
    image: informs-app
    env_file:
      - env/django.env
    entrypoint: /opt/app/docker-entrypoint.sh
    command: bash -c "cd /opt/app/informs && coverage run --source='.' manage.py test $(find . -path ./tests -prune -o -name 'test*.py' -print | sed 's|^\./||; s|\.py$||; s|/|.|g') --settings=informs.settings && coverage report -m && coverage html"
    volumes:
      - informs_test_staticfiles:/opt/app/static_files
      - informs_test_db:/opt/app/db
      - test_certs:/opt/app/certs:z
      - ./reports:/opt/app/reports

volumes:
  informs_test_staticfiles:
  informs_test_db:
  test_certs:

networks:
  default:
    name: test_webhost
