"""
Django settings for informs project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import configparser
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Create logs directory path
LOGS_DIR = BASE_DIR / 'logs'

# Ensure logs directory exists
LOGS_DIR.mkdir(exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
ENV_NAME = os.environ.get('ENV_NAME', 'sand')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# We default to True in development if not set, but in production this should be False
if os.environ.get('DJANGO_DEBUG', 'True').lower() == 'false':
    DEBUG = False
else:
    DEBUG = True

# Debug Toolbar settings - requires DEBUG to be True
DEBUG_TOOLBAR = False
if DEBUG and os.environ.get('DEBUG_TOOLBAR', 'False').lower() == 'true':
    DEBUG_TOOLBAR = True

SERVERNAME1 = os.environ.get('SERVERNAME1', 'localhost')
SERVERNAME2 = os.environ.get('SERVERNAME2', 'localhost')

ALLOWED_HOSTS = ["127.0.0.1", "localhost", SERVERNAME1, SERVERNAME2, "informs"]

SITE_ID = 1

ORGANIZATION_URL = os.environ.get('ORGANIZATION_URL', 'https://example.com')
ORGANIZATION_NAME = os.environ.get('ORGANIZATION_NAME', 'Informs @ SheerIoT')

SITE_IMAGE_URL = os.environ.get('SITE_IMAGE_URL', '')
# BANNER_COLOR = os.environ.get('BANNER_COLOR', '#0a1856')
COLOR_MODE = os.environ.get('COLOR_MODE', 'light')
BANNER_COLOR_LIGHT = os.environ.get('BANNER_COLOR_LIGHT', '#f8f9fa')
BANNER_COLOR_DARK = os.environ.get('BANNER_COLOR_DARK', '#212529')

if COLOR_MODE == 'dark':
    BANNER_COLOR = BANNER_COLOR_DARK
    NAVBAR_THEME = 'navbar-dark'
else:
    BANNER_COLOR = BANNER_COLOR_LIGHT
    NAVBAR_THEME = 'navbar-light'


# Read version from file
# try:
#     # Corrected path for within the Docker container
#     with open(os.path.join(BASE_DIR, 'app_version.txt'), 'r') as f:
#         APP_VERSION = f.read().strip()
# except FileNotFoundError:
#     APP_VERSION = '1.0'
# APP_VERSION is set later with STATIC_VERSION timestamp

# CSRF settings
CSRF_TRUSTED_ORIGINS = []

# Add servernames only if they're not localhost (avoid duplicates)
if SERVERNAME1 and SERVERNAME1 != 'localhost':
    CSRF_TRUSTED_ORIGINS.extend([
        'https://' + SERVERNAME1,
        'http://' + SERVERNAME1,
    ])

if SERVERNAME2 and SERVERNAME2 != 'localhost':
    CSRF_TRUSTED_ORIGINS.extend([
        'https://' + SERVERNAME2,
        'http://' + SERVERNAME2,
    ])

# Always include localhost origins
CSRF_TRUSTED_ORIGINS.extend([
    'http://127.0.0.1',
    'http://localhost',
])

CSRF_COOKIE_SECURE = False if DEBUG else True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_COOKIE_NAME = 'csrftoken'

# CORS Settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS.extend(['http://localhost:*', 'http://127.0.0.1:*'])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party
    'django_bootstrap_icons',
    'django_q',
    'django_filters',
    'auditlog',
    'tz_detect',
    'crispy_forms',
    'crispy_bootstrap5',
    'mathfilters',
    'corsheaders',
    'widget_tweaks',
    'meta',
    'django_htmx',
    'accounts.apps.AccountsConfig',
    'aidrequests.apps.AidRequestsConfig',
    'takserver.apps.TakServerConfig',
    'django_countries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'tz_detect.middleware.TimezoneMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

if DEBUG_TOOLBAR:
    INSTALLED_APPS.append('debug_toolbar')
    INSTALLED_APPS.append('template_profiler_panel')
    # Insert after AuthenticationMiddleware so we can check request.user
    try:
        auth_idx = MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware')
        MIDDLEWARE.insert(auth_idx + 1, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    except ValueError:
        MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

    # Internal IPS for Docker
    INTERNAL_IPS = [
        "127.0.0.1",
        "localhost",
    ]
    # Add the docker container IP
    import socket
    try:
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
        INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]
    except Exception:
        pass

    # Show toolbar only if user is logged in
    def show_toolbar(request):
        if request.user.is_authenticated:
            return True
        return False

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': show_toolbar,
    }

    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
        'template_profiler_panel.panels.template.TemplateProfilerPanel',
    ]

ROOT_URLCONF = 'informs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'informs' / 'templates',
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'informs.context_processors.server_hostname',
                'informs.context_processors.global_template_variables',
                'aidrequests.context_processors.fieldops_active',
                'aidrequests.context_processors.field_op_context',
            ],
            'builtins': [
                'django.templatetags.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'informs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

SQLITE_FILE = os.environ.get('SQLITE_FILE', BASE_DIR / 'db.sqlite3')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'NAME': SQLITE_FILE
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/opt/app/static_files/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Certificate storage for TAK Servers (Docker volume mount)
CERTIFICATE_STORAGE_ROOT = '/opt/app/certs'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Template Pack
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Sessions
SESSION_ENGINE = "django.contrib.sessions.backends.file"
SESSION_COOKIE_AGE = 1 * 24 * 60 * 60  # 1 day cookie
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = False if DEBUG else True  # Set to False for HTTP in development

DATA_UPLOAD_MAX_NUMBER_FIELDS = 500
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB max upload size

# BOOTSTRAP5 = {
#     "css_url": {
#         "href": "{% static 'css/custom-bootstrap.css' %}",  # your custom CSS file
#     },
# }

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'

# MAPS
AZURE_MAPS_STATIC_URL = 'https://atlas.microsoft.com/map/static'
MAPS_PATH = 'media/maps'

# django-q configuration
Q_CLUSTER = {
    'name': 'ORM',
    'workers': 1,
    'timeout': 180,
    'retry': 300,
    'queue_limit': 500,
    'bulk': 10,
    'orm': 'default',
    # 'sync': DEBUG,
    'scheduler': True,
    'catch_up': False,
    'label': 'Default ORM Queue'
}

# Email Setup
MAIL_FROM_DOMAIN = os.environ.get('MAIL_FROM_DOMAIN', 'example.com')
MAIL_FROM_USER = os.environ.get('MAIL_FROM_USER', 'noreply')
MAIL_FROM_KEY = os.environ.get('MAIL_FROM_KEY', '')
MAIL_FROM = f'{MAIL_FROM_USER}@{MAIL_FROM_DOMAIN}'
MAIL_TO_TEST = os.environ.get('MAIL_TO_TEST', '')
MAIL_ENDPOINT = os.environ.get('MAIL_ENDPOINT', '')

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ['true', '1']
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')
REPLY_TO_EMAIL = os.environ.get('REPLY_TO_EMAIL')

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'cot_format': {
            'format': '[{asctime}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'app.log'),
            'formatter': 'verbose',
        },
        'cot_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'cot_messages.log'),
            'formatter': 'cot_format',
        },
        "null": {
            "class": "logging.NullHandler",
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'cot': {
            'handlers': ['cot_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        "django.security.DisallowedHost": {
            "handlers": ["null"],
            "propagate": False,
        },
    },
}

# Azure Maps API key
AZURE_MAPS_KEY = os.environ.get('AZURE_MAPS_KEY', '')

# Security settings
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allow same origin framing (for maps, etc.)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = False if DEBUG else True  # Don't redirect to HTTPS in development
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# read in icons for TAK
# CoT Icon settings
icons_config = configparser.ConfigParser()
icons_config.read(os.path.join(BASE_DIR, 'takserver/cot_icons.ini'))
COT_ICONS = {key: value for key, value in icons_config.items('Icons')}
FIELD_OP_ICON_DEFAULT = 'blob_dot_yellow'
# ic(COT_ICONS)

# Static Version - timestamp generated at startup for cache busting
from datetime import datetime
STATIC_VERSION = datetime.now().strftime('%Y%m%d%H%M%S')
APP_VERSION = STATIC_VERSION

# PYTAK_FLUSH_TIMEOUT = 40 # seconds

# TAKMesh Gateway API URL (internal Docker network)
TAKMESH_API_URL = os.environ.get('TAKMESH_API_URL', 'http://takmesh:8090')
